name: Deploy to Kubernetes (Hot)

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  IMAGE_NAME: my-app
  IMAGE_TAG: ${{ github.sha }}
  REGISTRY: ghcr.io
  IMAGE_FULL: nginx:latest
  HOT_KUBECONFIG: ${{ secrets.KUBE_CONFIG_HOT }}

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            # - name: Login to GitHub Container Registry
            #   uses: docker/login-action@v3
            #   with:
            #       registry: ghcr.io
            #       username: ${{ github.actor }}
            #       password: ${{ secrets.GITHUB_TOKEN }}

            # - name: Build and push Docker image
            #   uses: docker/build-push-action@v5
            #   with:
            #       context: .
            #       push: true
            #       tags: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    deploy-hot:
        needs: build-and-push
        runs-on: ubuntu-latest
        environment: production-hot
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Kubeconfig
            run: |
              mkdir -p $HOME/.kube
              echo "${{ secrets.KUBE_CONFIG_HOT }}" > $HOME/.kube/config
              chmod 600 $HOME/.kube/config

          - name: Deploy to Hot Cluster
            run: |
              kubectl apply -f k8s/